### ISSUE TITLE
[request] set limit number of ratings displayed

### ISSUE THREAD

**Issue by omega3** [jerryzhou196/seepreviousratings#12]
When card history is long also there are a lot of ratings displayed:
https://i.imgur.com/lDGsoNt.png

Would be useful to have option to limit how many ratings are displayed, for example the last 5. This would be still useful information but at the same time not so eye catching on card, let say more discreet.

**Comment by jerryzhou196** [comment]
This is a really clever idea and I'll look into implementing it ASAP. As a temporary fix, you can go into the addon config to toggle an option which hides the reviews done in the learning stage. 
I will credit you in the credits section - thank you again!

**Comment by devinmugen** [comment]
This feature has been added.

**Comment by devinmugen** [comment]
Please give a response. @jerryzhou196
