### ISSUE TITLE
[REQUEST] Option to display rating history on card front

### ISSUE THREAD

**Issue by saxoncameron** [jerryzhou196/seepreviousratings#5]
It'd be nice to have the option to display the rating history element on the front of the card, in addition to having it on the back of the card.

**Comment by jerryzhou196** [comment]
For sure. I am updating it right now to show by default as many people requested that feature. I've also added the ease and interval in the tooltip. Should be updated soon!

**Comment by jerryzhou196** [comment]
Just updated the add-on so that it should default show for both the front and the back. Just click "Check For Updates" in the anki addon tab to get the newest version. Tell me your thoughts!

**Comment by saxoncameron** [comment]
Thanks for the fast turnaround @jerryzhou196! I've updated and restarted, but unfortunately it doesn't appear on the front of my cards :/

**Comment by jerryzhou196** [comment]
That's super weird. I think it might have something to do with config data being saved. Could you check if the addon settings display "constantly-show-addon": "true"?

![image](https://user-images.githubusercontent.com/46613983/127940144-bf8a96f6-600e-4592-9211-b1f68013df81.png)

Tell me how it goes!

**Comment by saxoncameron** [comment]
Yep, I had that checked.

For what it's worth, I saw the card review element flash when the card first loads, then disappear. The same thing happens when I mark the card as pass/fail: the card review element flashes visible for a moment before the back of the card is displayed. Display on the card back is unaffected and is working fine as normal.

I thought perhaps it was due to a clash with another addon I have installed, but after toggling a couple of them off and the issue persisting I gave up that line of debugging. :/

**Comment by jerryzhou196** [comment]
I really appreciate that you tried though! I will definitely look into this and try to get it figured out!

**Comment by jerryzhou196** [comment]
If possible, could you send me a screenshot of your addons. I can probably look through their source code to see for conflicts! :)

**Comment by saxoncameron** [comment]
Now that's dedication! Here's my Anki debug info, happy hunting:

```
    Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
    Platform: Mac 10.15.7
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2021-08-02 13:12:37
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AJT Browser Play Button ['182970692', 2021-07-31T04:32, 'None', '']
    AJT Flexible Grading ['1715096333', 2021-07-31T05:02, 'None', mod]
    Adjust Sound Volume ['2123044452', 2021-05-05T21:24, 'None', mod]
    AnkiWebView Inspector ['31746032', 2019-05-03T08:43, 'None', '']
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2021-07-29T22:55, 'None', '']
    Batch Editing ['291119185', 2019-06-03T04:47, 'None', '']
    Change note type respect field and card names ['513858554', 2020-03-09T19:47, 'None', '']
    Copy2Clipboard ['1525025114', 2018-11-30T06:51, 'None', mod]
    Japanese Card Randomizer ['1476821676', 2021-07-27T08:02, 'None', mod]
    Learn now Button ['1021636467', 2020-12-26T14:36, 'None', '']
    Migaku Dictionary ['1655992655', 2021-07-03T06:55, 'None', mod]
    Migaku Editor ['1051095155', 2021-06-29T12:06, 'None', mod]
    Migaku Japanese ['278530045', 2021-04-13T08:36, 'None', mod]
    Migaku Kanji ['Migaku Kanji', 0, 'None', mod]
    Migaku Retirement ['1666520655', 2021-01-14T11:37, 'None', mod]
    Migaku Vacation ['605638174', 2021-01-14T11:36, 'None', mod]
    Mortician ['1255924302', 2021-08-02T19:44, 'None', mod]
    Remaining time for Anki 21 ['1508357010', 2020-12-14T01:14, '20.12.13i151', '']
    Review Heatmap ['review_heatmap', 2020-04-30T23:23, 'None', '']
    See Previous Card Ratings in Reviewer ['1906641654', 2021-08-03T09:11, 'None', mod]
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-06-02T19:11, 'None', '']
    True Retention ['613684242', 2017-11-20T07:43, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1021636467 1046608507 1051095155 1255924302 1436550454 1476821676 1508357010 1525025114 1655992655 1666520655 1715096333 182970692 1906641654 2123044452 278530045 291119185 31746032 513858554 605638174 613684242
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
```

**Comment by jerryzhou196** [comment]
I think the issue might be with a hook that was just recently implemented in Anki 2.1.45 
If you are interested in getting the all-display feature you will probably have to update your Anki version to 2.1.45
I think it should work then!

**Comment by jerryzhou196** [comment]
Okay so sorry for spamming you so much but I think it might not be a conflict with your addons, but rather your card templates. I downgraded to 2.1.35 and downloaded your addons but I still see the Card History tab. :) If possible, could you send me your card templates and styling? (also which card type are you using?) I'm pretty sure lots of others are having a similar issue so I will try to get on top of this as fast as possible. Cheers!

**Comment by saxoncameron** [comment]
Haha look at you go; awesome. The main note types I use are the JLPT Tango and Migaku Sentence note types, which I've modified slightly. Here's a sample note of each:

[Selected Notes.apkg.zip](https://github.com/jerryzhou196/seepreviousratings/files/6920506/Selected.Notes.apkg.zip)

**Comment by saxoncameron** [comment]
👋 Hello! I noticed the update and can confirm it's now working for me. Feel free to close the issue if you are satisfied.

**Comment by saxoncameron** [comment]
Closing this, as it's evidently been implemented and fixed. 🚀
