### ISSUE TITLE
Not showing after latest update

### ISSUE THREAD

**Issue by Rekhyt370** [jerryzhou196/seepreviousratings#6]
Hello, as the title already says, the ratings don't show in my anki after the latest update.
I tried it with the new option on/off and also with all other addons disabled. It doesn't work for all my note types.
I'm using 2.1.44.

Would be nice if you could fix it or tell me what I have to do. Great addon!

**Comment by schmitz1** [comment]
Yes. I've the same version and the addon is not showing for me too.

**Comment by jerryzhou196** [comment]
Thank you so much for bringing this up - will downgrade to 2.1.44 and try to see what's going on. Update to fix should be out soon!

**Comment by jerryzhou196** [comment]
@Rekhyt370 @schmitz1 Thank you again. I reverted some of the addon CSS injection to a past version. Tell me your thoughts! Cheers!

**Comment by Rekhyt370** [comment]
Works again as intended. Thanks for being such an active addon creator. : )

**Comment by saxoncameron** [comment]
@jerryzhou196 looks like this issue has been resolved. You can probably close this (and maybe some others) to keep your issue queue containing only relevant/active issues. :)

**Comment by schmitz1** [comment]
Thank you for fix it, now the addon is working fine.

**Comment by jerryzhou196** [comment]
@saxoncameron Thank you for the advice! @schmitz1 Glad to know it's working again. I will definitely start to close the issue queue so it's easier. (sort of new to this whole issue thing so I actually really appreciate the advice) Cheers!
