### ISSUE TITLE
[BUG] New cards display review histories of the previous card

### ISSUE THREAD

**Issue by saxoncameron** [jerryzhou196/seepreviousratings#8]
Have been able to replicate this issue a couple of times now. If a new card comes up, it will display/retain the review history of the previous (not new) card.

![Pasted_Image_4_8_21__1_31_pm](https://user-images.githubusercontent.com/3240185/128118166-809c58f6-b3aa-43a2-b061-1c56723440a4.png)

Here's the previous (not new) card that it's keeping the history of:

![Screen Shot 2021-08-04 at 1 32 10 pm](https://user-images.githubusercontent.com/3240185/128118237-44eafd1c-a53e-4a70-9c92-2e4879a22463.png)

I've noticed this is not a problem if the VERY FIRST card in your review queue is new. Seems to be a retention problem, or a matter of not-clearing the review history element when a new card with no history appears.

**Comment by jerryzhou196** [comment]
This is a super good bug that I am surprised nobody has noticed earlier. The fix will be out very soon as it should just be a few lines of code. Thanks again mate!

**Comment by saxoncameron** [comment]
This has evidently been fixed. Nice work 👌 🔥
