### ISSUE TITLE
[BUG] [STYLE] Some card global styles override review history styles

### ISSUE THREAD

**Issue by saxoncameron** [jerryzhou196/seepreviousratings#9]
Hello! I've noticed that the review history element looks strange on one of my note types, which is from Migaku (another third party language-learning community with a growing following). See how it's mainly margins that have been overridden:

![Screen Shot 2021-08-05 at 12 55 57 pm](https://user-images.githubusercontent.com/3240185/128284142-a7d34714-ab5b-43cc-8e0e-2ff3ef8647d8.png)

## How to fix

I inspected to see which styles specifically, and deduced the following:

![Pasted_Image_5_8_21__12_58_pm](https://user-images.githubusercontent.com/3240185/128284185-f81cea3a-4f57-49b9-a30c-dfe70ac9d7ae.png)
![Pasted_Image_5_8_21__12_57_pm](https://user-images.githubusercontent.com/3240185/128284193-ca799d85-cebc-4de6-851d-be7044858f9b.png)
![Pasted_Image_5_8_21__12_57_pm-2](https://user-images.githubusercontent.com/3240185/128284197-fc2cadce-073e-4173-b7de-8e554a825612.png)

If you append `!important` to the above styles as shown (or indeed to ALL your styles if you really want to resist card global styles across the board) then it looks normal.

Thanks!

**Comment by jerryzhou196** [comment]
Oh my god this is so useful holy crap. This pretty much solves 90% of the CSS formatting issues we have been having for the addon where global stylings screw it up! I will implement this ASAP. Once again coming in clutch @saxoncameron - cheers mate!

**Comment by FrozenKite** [comment]
I also ran into this issue; for me it was the line spacing that was overridden by the card style.

![linespace](https://user-images.githubusercontent.com/65102280/128577838-2d730e9c-dff7-4d5b-ad55-9dc9afd0a0fc.png)

To fix this I just added in `line-height: normal;` to the `.tooltiptext` CSS rule.

(And you may want to make it `line-height: normal !important;` based on the above issue)

**Comment by jerryzhou196** [comment]
Thank you so much @FrozenKite for going above and beyond with a solution. I have implemented you and saxon's solution into the code and credited you. Update will be out by today.

**Comment by FrozenKite** [comment]
Thanks @jerryzhou196!

(P.S. are you planning to push the recent changes to Github, then people could make pull requests on `main` 🙃)

**Comment by jerryzhou196** [comment]
Totally. Sorry about not doing that earlier! Will push it right now!

**Comment by saxoncameron** [comment]
Can confirm that the latest update fixes the style issues I was having. 👍

**Comment by FrozenKite** [comment]
Actually I just tested it and it turns out the outer container also fell victim to my card's line height:

![bugthing](https://user-images.githubusercontent.com/65102280/128808566-2a40e69f-65e5-4565-a130-6f7fbe6fbeb9.png)

The fix is to put `line-height: normal !important` for the `#legend` rule as well.

(Sorry, should have noticed it earlier)

**Comment by jerryzhou196** [comment]
For sure and please don't apologize! I really appreciate that you are fixing the add on 😅. (I noticed this with my cloze styling too) Update will be out with the line height on the legend container too.
